/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author temporal2
 */
public class NuevoJuego extends javax.swing.JFrame {

    /**
     * Creates new form NuevoJuego
     */
    public NuevoJuego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEsturLeng = new javax.swing.JButton();
        btnMate = new javax.swing.JButton();
        btnQuimica = new javax.swing.JButton();
        btnculturaG = new javax.swing.JButton();
        btnbBiologia = new javax.swing.JButton();
        btnGeografia = new javax.swing.JButton();
        btnHistoria = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEsturLeng.setText("ESTRUCTURA DE LA LENGUA");
        btnEsturLeng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsturLengActionPerformed(evt);
            }
        });

        btnMate.setText("MATEMATICAS");
        btnMate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMateActionPerformed(evt);
            }
        });

        btnQuimica.setText("QUIMICA");
        btnQuimica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuimicaActionPerformed(evt);
            }
        });

        btnculturaG.setText("CULTURA GENERAL");
        btnculturaG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnculturaGActionPerformed(evt);
            }
        });

        btnbBiologia.setText("BIOLOGIA");
        btnbBiologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbBiologiaActionPerformed(evt);
            }
        });

        btnGeografia.setText("GEOGRAFIA");
        btnGeografia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeografiaActionPerformed(evt);
            }
        });

        btnHistoria.setText("HISTORIA");
        btnHistoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnculturaG)
                .addGap(145, 145, 145))
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(btnEsturLeng)
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnQuimica)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnHistoria)
                                .addComponent(btnMate)
                                .addComponent(btnbBiologia))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGeografia)
                                .addGap(24, 24, 24)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEsturLeng)
                .addGap(18, 18, 18)
                .addComponent(btnMate)
                .addGap(20, 20, 20)
                .addComponent(btnQuimica)
                .addGap(18, 18, 18)
                .addComponent(btnbBiologia)
                .addGap(18, 18, 18)
                .addComponent(btnGeografia)
                .addGap(18, 18, 18)
                .addComponent(btnHistoria)
                .addGap(18, 18, 18)
                .addComponent(btnculturaG)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEsturLengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsturLengActionPerformed
        ESTRUCTURALENG abrir= new ESTRUCTURALENG();
        abrir.setVisible(true);
        this.setVisible(false);        
    }//GEN-LAST:event_btnEsturLengActionPerformed

    private void btnMateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMateActionPerformed
       MATEMATICAS abrir= new MATEMATICAS();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMateActionPerformed

    private void btnQuimicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuimicaActionPerformed
        QUIMICA abrir= new QUIMICA();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnQuimicaActionPerformed

    private void btnculturaGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnculturaGActionPerformed
        CULTURAGENERAL abrir= new CULTURAGENERAL();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnculturaGActionPerformed

    private void btnbBiologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbBiologiaActionPerformed
        BIOLOGIA abrir= new BIOLOGIA();
        abrir.setVisible(true);
        this.setVisible(false);        
    }//GEN-LAST:event_btnbBiologiaActionPerformed

    private void btnGeografiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeografiaActionPerformed
        GEOGRAFIA abrir= new GEOGRAFIA();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnGeografiaActionPerformed

    private void btnHistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoriaActionPerformed
        HISTORIA abrir= new HISTORIA();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHistoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEsturLeng;
    private javax.swing.JButton btnGeografia;
    private javax.swing.JButton btnHistoria;
    private javax.swing.JButton btnMate;
    private javax.swing.JButton btnQuimica;
    private javax.swing.JButton btnbBiologia;
    private javax.swing.JButton btnculturaG;
    // End of variables declaration//GEN-END:variables
}
